#! /usr/bin/env python
# encoding: utf-8

bld.program(
    features='cxx test',
    source=['jutils_tests.cpp'] + bld.path.ant_glob('src/*.cpp'),
    target='jutils_tests',
    use=['jutils', 'gtest'])
